ansible_become_pass: ENC[AES256_GCM,data:0bXQZBGq7mrzxW3qhcG7uEtoBLywSfFs1IdHuwykBBDgFRJ/tj/O1IAPyT/mhqHQ,iv:PvjpEyo7WMMDScxeLhg0q0sLL5sbZHcudYDQ9SYlfXo=,tag:Z1h6gOWAdrBeGTNWje1yBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsm33nxu0wqqupz454shqhdf26h33qcf4rwpaj2w8h47heghyy0sreh5j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa2lOeSsvSDhQNWNKWXlh
            MlpIZE1Tb2tTd1RGeE5VRDBReSt5NHJscDJvCkM4eDhWZkxLRWFLU1grY1RObDlT
            d25TNTNBMklNZWx3aDh3RzkyLzVPVFUKLS0tIFZqVk56YlhMbTN6dEg5dUl2WGgy
            N25yTkFiZFNhNm1tVkE4bXJiM0RkSmcKA00nhJxSwaxVKV8D2RJFsgVom7t2fRnA
            TYrsjhrXat2HkbicaJ2AOogvNxaav7auw6GsO5jXlqFi+SpxCSQOog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T17:03:15Z"
    mac: ENC[AES256_GCM,data:eLdL4kdPTJUBvbV3Ksq29XcXwHtaDXbCIEDwHalcj+d53lhyTBguh7VYGvohijtKdtd7llu8xvDn/r0rf0msoBHqiKZyICCuNN/K2zoP+O15BozbOJ+HVN5+mRh3YFmwPpTkqpYZkALKK/G16z4i69CqrVM6roOdgZcvcg43elk=,iv:4hoejRaijD71nBmtEB7OXu2NPrBPeKcQmVYxd/hMukU=,tag:DWEEj0ICmwzHsPJoONp1ug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
