---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: yeboster
spec:
  interval: 10m0s
  path: ./k8s/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: yeboster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
