apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: todoist-actions
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: github
  url: ssh://github.com/Yeboster/todoist-actions.git
