apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:+c5FGBTJsGm3Tsft,iv:zbX3AewAvePmkOlmu/Tbrnx/41ntbJb+/3CQbFAPt+A=,tag:ZPHwpxPtRYxi6Y3QTuERqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsm33nxu0wqqupz454shqhdf26h33qcf4rwpaj2w8h47heghyy0sreh5j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWldQTWdWSHRIY0YvRlN2
            dThSd1UrV3R4bzhSWnNlM1RKQUluaEs1TldrCk5NaGgwWEZYTWsrODF5Z3Zaakh3
            SXhHNDNtR3dLbUVRU1hqYit5TXNRUlUKLS0tIElON05GTEVHakpUcFJzS1lETkJU
            YldkYk5YMXhhbjRzN0VrQk9YWlBjemcK8I8sVZ1jdSqhHO7Hzl0yzOadeNGEWLVO
            HZpZ7UbdBGlgcJBlSiPODsXkQlQg9TqlcQaj2l3B/B0GG3x2k3kunQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T17:03:49Z"
    mac: ENC[AES256_GCM,data:snleZcVKMyt8WFAwn/Ap86a2LAsalHctJTL1Av7bdHxcY3vi7Tl6TLIbjbPZwoZoPMBus3RGxymMjM79MZCkK16WeITGw//w8BmVmIxQdFZ7f/+1Y+nF5SaRUB4ZPSXGJkBu5XFzq8/cCWdSMD3slLgBndhnPIrOvm1Rs45q//A=,iv:gxHIaBQk3tSQgQ6I2yib6Dvo2Xfj5AZeVLo0zGAm4bo=,tag:F/tWf2uwnmQE0zdLd8Xg9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
