apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:cdRpCLSqQFnswUlEin/HFgYs3ozm/idiclNlOng9pORuquFq,iv:5FEqAT/TqPSlL4IJO1fYweQ0ySjgraHy2TCmzTkAI2U=,tag:ltcR6XmwU7Qy3Tnx4NTkQg==,type:str]
    credentials.json: ENC[AES256_GCM,data:X/ZCGviH8Agck7THjjEW4fqwrTliE7x/tlQ96C5i4Mx8nAgWfGjDHcdcUZM8GKAyvG7OW85dxWhQPq1xosKKKxWWWRTfvoA5agR/5qjxM+fgejcPcvvdxuL4jY5IUThK9mBWEd19xJiVb/u6TkUwaFD/C73PvDGupP+syopkhFoY63BYGhCTmXq+eKZ3xafpqY+puADBGSLWc8m6R12rS+7/4TNcYubGfD/Pt1Es8g==,iv:zTEIPx1coJBr4JyiVSowqtWpTCK+/V3ze+vEjshjZXk=,tag:cV2VPcu77TFlxUqmpc/mog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsm33nxu0wqqupz454shqhdf26h33qcf4rwpaj2w8h47heghyy0sreh5j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SE1IbG9HVnVaaTRBVno2
            bzRxRUZOZko3WHdoVEFyaGhYamRsL0RlNlRrCnZsZkF1eUlsRS8yMWUxT2hJd1Zs
            ckhaYnpuQTdzVkZmbDV3QmFUbWorMzAKLS0tIHRXV1JoYU5KOVdpeEhBL1Evd1dp
            RC9iZy92OTdPTUhQMU8vY3N6OHFkT3cKq2exe8rCSVVyfPYqfOGXAPe6tusSkk9q
            KsWlpCbvYDVRrQRiENfq9EPdra2NQkv+2r+hg/ZFR5eF4nDJKEWvBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T17:03:50Z"
    mac: ENC[AES256_GCM,data:tY5XWoHZC5tYWv2vmdEtXWNMgVLodI0VRii3Ny9rFeDqZlXM4Kh94FBdMhTkQdI4EI1yoP13YC8OhPLkcMibFXNrtIetlYsJOPkFpB5Kb45BIkUwvbASswlLlAp4frxJqbBBflliJV3tB9+fUYgBk2ksJzsXQK/l7zp7hZI+K3g=,iv:Tt2YNZDvPai3aAGEqImGgyxpTb3c2fzeDlpiHUAO/D4=,tag:t4DIBaiWwoD1Clr4343+tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
